"use client";

import { jsPDF } from "jspdf";

import type { AIReport, Project, ProjectSummary } from "@/lib/types";
import { formatDate } from "@/lib/utils";

interface ExportPdfArgs {
  project: Project;
  summary: ProjectSummary;
  report: AIReport;
}

/**
 * Render an AI advisor report to a printable PDF and trigger a download.
 *
 * Uses jsPDF's built-in UTF-8 Latin font which already covers the basic
 * Vietnamese diacritics we emit.  For more complex unicode (CJK, emoji)
 * we strip to ASCII so the export always succeeds.
 */
export function exportReportToPdf({ project, summary, report }: ExportPdfArgs) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  function addPageIfNeeded(neededHeight: number) {
    if (y + neededHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  }

  function writeLine(text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number]; spacing?: number } = {}) {
    const { size = 11, bold = false, color = [31, 41, 55], spacing = 4 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(stripVietnamese(text), maxWidth);
    for (const line of lines) {
      addPageIfNeeded(size + spacing);
      doc.text(line, margin, y);
      y += size + spacing;
    }
  }

  function blank(sp = 8) {
    y += sp;
  }

  function horizontalRule() {
    addPageIfNeeded(20);
    doc.setDrawColor(229, 231, 235);
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;
  }

  // === Header ===
  writeLine("Smart Student Project Manager", { size: 18, bold: true, color: [99, 102, 241] });
  writeLine("Báo cáo tiến độ do AI tạo", { size: 11, color: [107, 114, 128] });
  blank(4);
  horizontalRule();

  // === Project info ===
  writeLine("Dự án", { size: 9, color: [107, 114, 128] });
  writeLine(project.title, { size: 14, bold: true });
  writeLine(project.description || "(không có mô tả)", { size: 10, color: [75, 85, 99] });
  blank(2);
  writeLine(`Deadline: ${formatDate(project.deadline)}`, { size: 10, color: [75, 85, 99] });
  writeLine(`Báo cáo tạo lúc: ${formatDate(report.created_at, "dd/MM/yyyy HH:mm")}`, { size: 10, color: [75, 85, 99] });
  blank(8);

  // === Stats box ===
  writeLine("Thống kê nhanh", { size: 9, color: [107, 114, 128] });
  const stats = [
    `Tổng task: ${summary.total_tasks}`,
    `Hoàn thành: ${summary.completed_tasks}`,
    `Quá hạn: ${summary.overdue_tasks}`,
    `CPM duration: ${summary.cpm_project_duration ?? "—"} ngày`,
    `Rủi ro trễ: ${((summary.cpm_delay_risk ?? 0) * 100).toFixed(0)}%`,
  ];
  for (const s of stats) writeLine("• " + s, { size: 10 });
  blank(8);
  horizontalRule();

  // === Report body (rendered as plain text with headings detected) ===
  writeLine("Báo cáo chi tiết", { size: 9, color: [107, 114, 128] });
  blank(4);

  const lines = (report.report_text || "").split("\n");
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.trim() === "") {
      blank(4);
      continue;
    }
    if (line.startsWith("# ")) {
      blank(6);
      writeLine(line.slice(2), { size: 14, bold: true, color: [17, 24, 39] });
      blank(2);
    } else if (line.startsWith("## ")) {
      blank(4);
      writeLine(line.slice(3), { size: 12, bold: true, color: [31, 41, 55] });
    } else if (line.startsWith("### ")) {
      blank(2);
      writeLine(line.slice(4), { size: 11, bold: true });
    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      writeLine("  •  " + line.replace(/^[-•]\s+/, ""), { size: 10 });
    } else if (/^\d+\.\s/.test(line)) {
      writeLine("  " + line, { size: 10 });
    } else {
      writeLine(line, { size: 10 });
    }
  }

  // === Footer on every page ===
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `${project.title} · Trang ${i}/${pages}`,
      margin,
      pageHeight - 20
    );
    doc.text(
      "Generated by Smart Student Project Manager",
      pageWidth - margin,
      pageHeight - 20,
      { align: "right" }
    );
  }

  const filename = `bao-cao-${slugify(project.title)}-${formatDate(report.created_at, "yyyyMMdd-HHmm")}.pdf`;
  doc.save(filename);
}

function stripVietnamese(input: string): string {
  // jsPDF's default helvetica doesn't ship Vietnamese glyphs.  We do a
  // best-effort diacritic strip so the output remains readable.
  return input.normalize("NFD").replace(/[̀-ͯ]/g, "");
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}
